before:
  hooks:
    - ./scripts/build-cloud.sh {{ .Version }}

builds:
  - id: cloud
    skip: true # Skip building, we are doing this in the before hook
    no_unique_dist_dir: true
  - id: agent
    main: ./cmd/agent/main.go
    binary: serviceradar-agent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
  - id: poller
    main: ./cmd/poller/main.go
    binary: serviceradar-poller
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
  - id: dusk-checker
    main: ./cmd/checkers/dusk/main.go
    binary: serviceradar-dusk-checker
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
env_files:
  github_token: ~/.config/goreleaser/github_token
nfpms:
  - id: cloud
    package_name: serviceradar-cloud
    file_name_template: "{{ .PackageName }}_{{ .Version }}"
    vendor: ServiceRadar
    homepage: https://github.com/mfreeman451/serviceradar
    maintainer: Michael Freeman <mfreeman451@gmail.com>
    description: ServiceRadar cloud service with web interface
    license: Apache 2.0
    formats:
      - deb
    dependencies:
      - systemd
    contents:
      - src: dist/cloud_linux_amd64_v1/serviceradar-cloud
        dst: /usr/local/bin/serviceradar-cloud
        file_info:
          mode: 0755
      - src: pkg/cloud/api/web/dist
        dst: /usr/local/share/serviceradar-cloud/web/dist
      - src: packaging/cloud/systemd/serviceradar-cloud.service
        dst: /lib/systemd/system/serviceradar-cloud.service
      - src: packaging/cloud/config/cloud.json
        dst: /etc/serviceradar/cloud.json
        type: config
    scripts:
      postinstall: packaging/cloud/scripts/postinstall.sh
      preremove: packaging/cloud/scripts/preremove.sh