FROM node:18-bullseye AS web-builder

WORKDIR /web-build

COPY web/package*.json ./
RUN npm install
COPY web/ .
RUN npm run build

FROM golang:1.23-bullseye

WORKDIR /src

RUN apt-get update && apt-get install -y \
    gcc \
    libc6-dev \
    libsqlite3-dev

COPY go.mod go.sum ./
RUN go mod download

COPY . .
COPY --from=web-builder /web-build/dist ./pkg/cloud/api/web/dist

RUN CGO_ENABLED=1 GOOS=linux GOARCH=amd64 \
    go build -o serviceradar-cloud ./cmd/cloud